language: node_js

node_js:
- "4.1"
- "4.0"
- "0.12"
- "0.11"
- "0.10"
branches:
only:
- master

install:
- npm install
- npm install mocha -g
script:
- npm run test
- npm run test1
- npm run test2
- npm run test3
- npm run test4
- npm run test5
- npm run test6
- npm run test7
- npm run test8
- npm run test9
- npm run test10
